### ISSUE TITLE
Not working on Python 3.3.0

### ISSUE THREAD

**Issue by studiosi** [jsargiot/ninja-debugger-plugin#3]
I get this traceback when starting Ninja with this plugin enabled. May it be because of the SimpleXMLRPCServer class merged into xmlrpc.server in Python 3.x?

Traceback (most recent call last):
  File "ninja_ide\core\plugin_manager.pyc", line 319, in load
  File "ninja_ide\core\plugin_manager.pyc", line 297, in _load_module
PluginManagerException: Error loading "debugger_plugin.Debugger": No module named SimpleXMLRPCServer

**Comment by jsargiot** [comment]
I haven't tested it in python 3. I'll take a look at this and let you know when i have something working on python 3. Thanks for your feedback.
