### ISSUE TITLE
not compatible with ninja IDE?

### ISSUE THREAD

**Issue by andeepeabody** [jsargiot/ninja-debugger-plugin#4]
Hello!

I downloaded your plug-in for Ninja and it's not working.  

Traceback (most recent call last):
  File "ninja_ide\core\plugin_manager.pyc", line 319, in load
  File "ninja_ide\core\plugin_manager.pyc", line 297, in _load_module
PluginManagerException: Error loading "debugger_plugin.Debugger": No module named SimpleXMLRPCServer

I have python 2.7 installed.  

Please help!
Thanks!
andee

**Comment by jsargiot** [comment]
I assume you're running on windows... but which version of Ninja-IDE are you using? Do you install it with the MSI or you running the source?

**Comment by andeepeabody** [comment]
MSI.   could that be the issue? Should I use the source code instead?

**Comment by jsargiot** [comment]
There some issues with the packaging of ninja not containing that specific
library... could you try with the source of ninja?

## 

Joaquin Sargiotto

**Comment by andeepeabody** [comment]
ok, got the source to install, and the debugger issue is now resolved.  now
on to the git and kai issues!  thanks!

**Comment by jsargiot** [comment]
Good to hear! Whatever feedback you have on the debugger is more than
welcome :)

## 

Joaquin Sargiotto

**Comment by Jean-Marie** [comment]
Hello !

I have the same problem as andeepeabody, same traceback message, Python 2.7, I am running under Windows XP, Ninja 2.3 installed through the msi file.
I have tried reinstalling Ninja from source files, but I am not a Python expert, I hardly know Linux, and I installed setuptools, that was OK, after which it said it needed the sip module, and I got lost there (needing to launch a make file... no explanation for windows), and my friends who know a little of Python & Linux sait I should abandon.
Do you have another solution for solving the SimpleXMLRPCServer module issue ?
Thank you

**Comment by jsargiot** [comment]
Sorry, There is no solution, and since the Ninja-IDE team is working on a new version with a fresh architecture I don't think it is possible to fix it. We'll have to wait for the next release I guess...

**Comment by Jean-Marie** [comment]
OK, I will have to do with another IDE for the moment, I will test Ninja with debugger plug-in when the next release of Ninja comes out
Thank you for your answer and, most of all, for the great work which you provide

**Comment by emwa** [comment]
Hi,
I'm trying to use the plugin but seems that I can't make it work properly.

1)put the break points
2) start de debugging file
... it doesn't stop on the break points but appear all the debugging options active

On Debian with: 
python 2.7
ninja-ide 2.3
ninja-debugger-plugin 0.4.2

same issue or a new one? don't have any visible error...
