### ISSUE TITLE
Cannot continue when no thread is selected

### ISSUE THREAD

**Issue by jsargiot** [jsargiot/ninja-debugger-plugin#7]
I try to continue with no thread selected in the thread list, nothing happens and the following exception is seen in the terminal:

```
Traceback (most recent call last):
  File "/home/daniel/.ninja_ide/addins/plugins/debugger_plugin/Debugger.py", line 477, in debug_cont
    self.debugger_adapter.resume_all()
  File "/home/daniel/.ninja_ide/addins/plugins/debugger_plugin/ndb3/rpc.py", line 254, in resume_all
    return self.__safe_call(self.remote.resume)
  File "/home/daniel/.ninja_ide/addins/plugins/debugger_plugin/ndb3/rpc.py", line 200, in __safe_call             
    return func(*args)                                                                                            
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__                                                  
    return self.__send(self.__name, args)                                                                         
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request                                                 
    verbose=self.__verbose                                                                                        
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request                                                   
    return self.single_request(host, handler, request_body, verbose)                                              
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request                                            
    return self.parse_response(response)                                                                          
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response                                            
    return u.close()                                                                                              
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close                                                      
    raise Fault(**self._stack[0])                                                                                 
xmlrpclib.Fault: <Fault 1: "<type 'exceptions.AttributeError'>:NdbThread instance has no attribute 'ndb_info'">  
```

Thanks to: Daniel Samu

**Comment by jsargiot** [comment]
Fixed.
